use eLib;
create table Books(id MEDIUMINT NOT NULL AUTO_INCREMENT,
    name CHAR(100) NOT NULL,
    path CHAR(200) NOT NULL,
    path_to_cover CHAR(200),
    driveLink CHAR(200),
    ebook TINYINT,
    pdf TINYINT,
    fiction TINYINT,
    mystery TINYINT,
    fantasy TINYINT,
    science_fiction TINYINT,
    non_fiction TINYINT,
    genre_fiction TINYINT,
    thriller TINYINT,
    romance TINYINT,
    young_adult_fiction TINYINT,
    crime_fiction TINYINT,
    literary_fiction TINYINT,
    horror_fiction TINYINT,
    history TINYINT,
    fairy_tale TINYINT,
    comic_book TINYINT,
    manga TINYINT,
    light_novel TINYINT,
    classic TINYINT,
  primary key (id));
